name: flutter_travel_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.2.0
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
     - family: Gilroy
       fonts:
        - asset: fonts/Gilroy-Regular.ttf
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
     - family: MyFlutterApp # the name of your font family
       fonts:
        - asset: fonts/MyFlutterApp.ttf # your font file name and the directory
          
  uses-material-design: true
  assets:
    - assets/backgrounds/intro.jpg
    - assets/icons/action.svg
    - assets/icons/star.svg
    - assets/icons/notif.svg

  
